# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPOC
  pod 'MobileFrameworkPOC', :path => '../MobileFrameworkPOC'
  target 'TestPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestPOCUITests' do
    # Pods for testing
  end

end
